package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/urfave/cli/v3"
)

const collectionHeader = `%% Generated by domusic

\header {
    title = "{{.title}}"
}

\paper {
    tocItemMarkup = \tocItemWithDotsMarkup
}
\layout {
    \context {
        \Score
        \autoPageBreaksOff
    }
}

\markuplist \table-of-contents

\pageBreak

%% The tunes
`

var collectionCmd = &cli.Command{
	Name:  "collection",
	Usage: "Generate a collection document given a number of files",
	Flags: []cli.Flag{
		&cli.StringFlag{
			Name:    "title",
			Aliases: []string{"t"},
			Value:   "Collection",
			Usage:   "collection title",
		},
	},
	Action: func(ctx context.Context, cmd *cli.Command) error {
		args := cmd.Args().Slice()
		title := cmd.String("title")
		data := map[string]any{
			"title": title,
		}

		template, err := executeTemplate(collectionHeader, data)
		errExit(err)

		files := []string{}
		for _, arg := range args {
			if strings.Contains(arg, "*") {
				f, _ := filepath.Glob(pathFromRoot(arg))
				files = append(files, f...)
			} else {
				files = append(files, arg)
			}
		}

		sort.Slice(files, func(i, j int) bool {
			return pathForSort(files[i]) < pathForSort(files[j])
		})

		for _, f := range files {
			fd, err := os.ReadFile(getSourcePath(f))
			errExit(err)
			matches := titleRx.FindSubmatch(fd)
			if len(matches) < 2 {
				msgExit(fmt.Sprintf("no title found in file: %s", f))
			}
			title := matches[1]
			template += fmt.Sprintf("\\tocItem \\markup \"%s\"\n", title)
			template += fmt.Sprintf("\\include \"%s\"\n\n", f)
		}

		fmt.Println(template)
		return nil
	},
}

func pathForSort(path string) string {
	return strings.Replace(filepath.Base(path), "!", "", -1)
}
